spring:
  datasource:
    url: ${DB_JDBC_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2s
      timeout: 1s
  jwt:
    secret: ${JWT_SECRET_KEY}
    token-milliseconds:
      rtk: 14 * 60 * 60 * 24 * 1000 # 14일
      atk: 60 * 60 * 3 * 1000 # 3시간
chatgpt:
  model : ${CHATGPT_MODEL}
  api-key: ${CHATGPT_KEY}
  url: ${CHATGPT_URL}
