spring:
  datasource:
    url: ${DB_JDBC_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2s
      timeout: 1s
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  batch:
    jdbc:
      initialize-schema: ALWAYS
    job:
      enabled: true

server:
  port: 9090

nutrition:
  service-key: ${SERVICE_KEY}
chatgpt:
  model : ${CHATGPT_MODEL}
  api-key: ${CHATGPT_KEY}
  url: ${CHATGPT_URL}

